name: CI/CD Pipeline

on:
  push:
    branches:
      - main # Chạy CI/CD khi có commit push vào nhánh 'main'
  pull_request:
    branches:
      - main # Chạy CI/CD khi có pull request gửi vào nhánh 'main'

jobs:
  build:
    runs-on: ubuntu-latest # Chạy trên hệ điều hành Ubuntu mới nhất

    steps:
      - name: Check out code
        uses: actions/checkout@v2 # Tải mã nguồn từ repository

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1 # Cài đặt Docker Buildx

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }} # Tên người dùng Docker (Lưu trữ trong Secrets của GitHub)
          password: ${{ secrets.DOCKER_PASSWORD }} # Mật khẩu Docker (Lưu trữ trong Secrets của GitHub)

      - name: Build and push Docker image
        run: |
          docker build -t my-app:${{ github.sha }} .  # Xây dựng Docker image với tag là commit sha
          docker push my-app:${{ github.sha }}  # Đẩy image lên Docker Hub

  deploy:
    runs-on: ubuntu-latest
    needs: build # Đảm bảo job deploy chỉ chạy sau khi job build thành công

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Deploy to Server
        run: |
          ssh -o StrictHostKeyChecking=no user@your-server-ip << 'EOF'
          docker pull my-app:${{ github.sha }}  # Kéo image mới từ Docker Hub
          docker stop my-app-container || true  # Dừng container hiện tại nếu có
          docker rm my-app-container || true  # Xoá container cũ
          docker run -d --name my-app-container -p 80:80 my-app:${{ github.sha }}  # Chạy container mới
          EOF
        env:
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }} # Cung cấp mật khẩu Docker từ GitHub Secrets
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }} # Cung cấp tên người dùng Docker từ GitHub Secrets
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }} # SSH Key để truy cập server

